### ISSUE TITLE
How to slow down the speed of the response?

### ISSUE THREAD

**Issue by mepc36** [NVIDIA/radtts#15]
Hey, I noticed sometimes that the results I get with `inference.py` are too fast to understand. Is there any argument I could pass in to slow down the speed of the response? I've played around with energy but so far, no luck.

Thank you!

**Comment by szprytny** [comment]
Hi. There is a parameter `token_dur_scaling` which you are probably looking for. If you want generated audio to be slower, you need to pass value higher than 1.

**Comment by mepc36** [comment]
@szprytny thank you so much! I'll try this and check back ASAP. Appreciate it!

**Comment by mepc36** [comment]
Thanks szprytny, it worked! You're the best.
