### ISSUE TITLE
Output of voice conversion has source model's timbre, not destination models timbre

### ISSUE THREAD

**Issue by mepc36** [NVIDIA/radtts#19]
Hey all, I'm running this basic command from the radtts repo [here](https://github.com/NVIDIA/radtts#inference-voice-conversion-demo):

```
python inference_voice_conversion.py --radtts_path RADTTS_PATH --radtts_config_path RADTTS_CONFIG_PATH --vocoder_path HG_PATH --vocoder_config_path HG_CONFIG_PATH --f0_mean=211.413 --f0_std=46.6595 --energy_mean=0.724884 --energy_std=0.0564605 --output_dir=results/ -p data_config.validation_files="{'Dummy': {'basedir': 'data/', 'audiodir':'22khz', 'filelist': 'vc_audiopath_txt_speaker_emotion_duration_filelist.txt'}}"
```

The problem is that audio output by this voice conversion command still uses the timbre of the .wav that I'm trying to transfer the style from. The timbre of the audio output does NOT sound like the radtts model's voice; it sounds like the file I passed in inside the validation files.

Can anyone please give me advice on what this means, and how to fix it? Is my radtts model not trained well enough? Am I doing it wrong?

I copied the file whose style I'm trying to transfer to /data/22khz, and then wrote its details inside `vc_audiopath_txt_speaker_emotion_duration_filelist.txt`. Any help would be greatly appreciated. Thanks!

**Comment by szprytny** [comment]
Have you set `speaker_id` in `vc_audiopath_txt_speaker_emotion_duration_filelist.txt` properly?
In that transcriptions file you have to specify id of the speaker you wish to be used in voice conversion.

**Comment by mepc36** [comment]
This was the problem, thank you @szprytny !
