### ISSUE TITLE
Question about spectrogram normalization

### ISSUE THREAD

**Issue by sjkoelle** [NVIDIA/radtts#28]
Since we are using a variety of pretrained vocoders, we need to be able to generate outputs with different spectrogram normalizations.  I notice that spectrogram normalization in 

https://github.com/NVIDIA/radtts/blob/main/data.py#L270

seems somewhat arbitrary.  What was the reason for this choice?

**Comment by kevjshih** [comment]
Great catch. That was actually a very rough normalization scheme to achieve roughly standarized inputs. You'll definitely be better off performing this step more diligently (with per-channel normalization parameters)  and keeping track of different standardization parameters for each vocoder setting you want to incorporate into your data.
